services:
  # --- BACKEND (Express) ---
  api:
    build: ./API-GLPI
    container_name: glpi-api
    image: glpi-api:latest
    restart: always
    environment:
      - SCHEDULE_INTERVAL=${SCHEDULE_INTERVAL:-30}
    ports:
      - "3000:3000"
    env_file: ./API-GLPI/.env

  # --- FRONTEND (Next.js) ---
  dashboard:
    build: ./Dashboard-Comment # Ajuste le chemin exact ici
    container_name: next-dashboard
    image: next-dashboard:latest
    restart: always
    environment:
      - API_BASE_URL=http://api:3000
      - SCHEDULE_INTERVAL=${SCHEDULE_INTERVAL:-30}
    ports:
      - "80:3001" # On mappe le port 80 (standard) vers le port 3001 de Next.js
    depends_on:
      - api